### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: rustsec/audit-check

### ISSUE THREAD

**Issue by istellino-chub** [rustsec/audit-check#19]
If you use the action `rustsec/audit-check` in the workflow github will show you the warning 

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20`

It will be great if you can updated to node 20

**Comment by Finomnis** [comment]
Is this repository still maintained? Last commit was about a year ago. I hope it is, I really like it.
