### ISSUE TITLE
audit-check default branch renamed from `master` to `main`

### ISSUE THREAD

**Issue by ZacJW** [rustsec/audit-check#26]
I've been getting GitHub Actions errors on my fork of tokio to do with audit-check

> Unable to resolve action `rustsec/audit-check@master`, unable to find version `master`

[Looks like tokio's been getting it too](https://github.com/tokio-rs/tokio/actions/workflows/audit.yml)

I don't see this action on the Marketplace when I [search for audit-check](https://github.com/marketplace?query=audit-check). Has it somehow been removed? I noticed the default branch for this repo is called `main`, not `master`. Was that changed around the 24th of September? That's when I started seeing the error.

**Comment by tarcieri** [comment]
That sounds like the date when I published v2.0.0 (#25). I didn't personally rename or delete any branches however, just tagged a `v2.0.0` release.

The development branch is indeed now named `main` as opposed to `master`. I'm not sure when that happened: this is a repo I inherited which is itself a fork of another repo, and I barely know what I'm doing with GitHub Actions.

I'm not sure what to do as a resolution here besides tell you to rename the branch in your config. We can mirror `main` as `master` for all eternity I guess. Renaming `main` back to `master` would break people who are using `main` in their configs.

**Comment by ZacJW** [comment]
![image](https://github.com/user-attachments/assets/72b98378-052f-43b0-a776-419a3878a8c3)
Looks like you did the rename on the 23rd

**Comment by ZacJW** [comment]
I think that rename is what broke tokio's security audit workflow. Personally I would weigh breaking 2 weeks of new users of audit-check against breaking years of existing users and find that changing the branch name back would be better than leaving as main. Though to be honest maybe this is just what we all get for using a branch rather than a tag like we should. I've renamed this issue to be about the rename since I think it's clear to me now that that's what caused the breakage.

**Comment by tarcieri** [comment]
I'm not sure how that happened. I don't remember doing it. I don't remember seeing any of the dialogs that the branch had been renamed. Perhaps npm did it? I don't know.

I renamed it back (which took a bit of doing, as I had to search around the UI for where to even do it, which again makes me wonder how it was renamed in the first place)

**Comment by kaizencc** [comment]
we've been using `main` for forever and just got broken by this rename to `master`... just a data point that the rename didn't just break 2 weeks of new users:

https://github.com/cdklabs/cdk-from-cfn/blob/8fad870a5b3cc604736d7ea0e7dff3dffd38b88e/.github/workflows/security-audit.yml

**Comment by tarcieri** [comment]
Ugh, I guess I can have the two mirror each other
